instrumentTypes:
  INSTRUMENT_TYPE_UNSPECIFIED: &unspecified 0
  INSTRUMENT_TYPE_BOND: &bond 1
  INSTRUMENT_TYPE_SHARE: &share 2
  INSTRUMENT_TYPE_CURRENCY: &currency 3
  INSTRUMENT_TYPE_ETF: &etf 4
  INSTRUMENT_TYPE_FUTURES: &futures 5
  INSTRUMENT_TYPE_SP: &sp 6
  INSTRUMENT_TYPE_OPTION: &option 7
  INSTRUMENT_TYPE_CLEARING_CERTIFICATE: &certificate 8
  INSTRUMENT_TYPE_INDEX: &index 9
  INSTRUMENT_TYPE_COMMODITY: &commodity 10

fromDate: &from_date "08.10.2024 13:00:00" # UTC
toDate: &to_date "09.10.2025 13:00:00" # UTC

stock:
  Sberbank:
    ticker: "SBER"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  T-Technology:
    ticker: "T"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  VTB:
    ticker: "VTBR"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  Yandex:
    ticker: "YDEX"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  X5:
    ticker: "X5"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  VK:
    ticker: "VKCO"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  Lukoil:
    ticker: "LKOH"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  PIK:
    ticker: "PIKK"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  Norilsk Nikel:
    ticker: "GMKN"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share

  SeverStal:
    ticker: "CHMF"
    interval: 2H
    from_date: *from_date
    to_date: *to_date
    instrument_type: *share